SOURCES = ./src/string/ft_strlcat.c \
./src/string/ft_strtrim.c \
./src/string/ft_strjoin.c \
./src/string/ft_strnstr.c \
./src/string/ft_toupper.c \
./src/string/ft_substr.c \
./src/string/ft_strncmp.c \
./src/string/ft_strlen.c \
./src/string/ft_itoa.c \
./src/string/ft_atoi.c \
./src/string/ft_strdup.c \
./src/string/ft_strchr.c \
./src/string/ft_strrchr.c \
./src/string/ft_strlcpy.c \
./src/string/ft_split.c \
./src/string/ft_tolower.c \
./src/fpointers/ft_strmapi.c \
./src/fpointers/ft_striteri.c \
./src/is/ft_isdigit.c \
./src/is/ft_isprint.c \
./src/is/ft_isalnum.c \
./src/is/ft_isascii.c \
./src/is/ft_isalpha.c \
./src/memory/ft_memcmp.c \
./src/memory/ft_memchr.c \
./src/memory/free_array.c \
./src/memory/ft_memmove.c \
./src/memory/ft_bzero.c \
./src/memory/ft_calloc.c \
./src/memory/ft_memcpy.c \
./src/memory/ft_memset.c \
./src/lists/ft_lstmap.c \
./src/lists/ft_lstsize.c \
./src/lists/ft_lstlast.c \
./src/lists/ft_lstclear.c \
./src/lists/ft_lstadd_front.c \
./src/lists/ft_lstiter.c \
./src/lists/ft_lstnew.c \
./src/lists/ft_lstdelone.c \
./src/lists/ft_lstadd_back.c \
./src/write/ft_putstr_fd.c \
./src/write/ft_putendl_fd.c \
./src/write/ft_putchar_fd.c \
./src/write/ft_putnbr_fd.c \
./src/debug/debug.c